Issue 644 - License
computationalgeography/lue pull request #666
Opened 2024-06-19 11:39 UTC by saeb-faraji-gargari

Closes #644

2024-06-19 14:58 UTC, kordejong requested changes
Thanks Saeb. I have some minor comments. Once handled  I will merge the PR.

2024-06-19 14:58 UTC, kordejong commented on LICENSE.txt
You can leave this file unchanged. It is our license. You don't need to refer to licenses of software we use.

2024-06-19 14:58 UTC, kordejong commented on document/doc/code/index.rst
- Please remove gperftools. It is a dependency of HPX.
- You may add that the libraries are used, depending on the targets built. (For example, Pybind11 is not used if the Python bindings are not built. GLFW, Vulkan and ImGui are not used if lue_view is not built.)
- Replace sentence starting with "Licenses for third-..." with "The licenses for these libraries can be found in the license directory of the LUE source repository." Maybe turn "license" in this sentence into a link.

2024-06-20 16:17 UTC, saeb-faraji-gargari commented on document/doc/code/index.rst
Please check the following table to list the libraries based on target builds

LUE_BUILD_DATA_MODEL and LUE_BUILD_FRAMEWORK
- `GDAL`_
- `HPX`_
- `Boost`_
- `HDF5`_
- `fmt`_
- `nlohmann-json3-dev`_

LUE_BUILD_VIEW
- `GDAL`_
- `HPX`_
- `Boost`_
- `HDF5`_
- `fmt`_
- `nlohmann-json3-dev`_
- `docopt`_
- `GLFW`_
- `ImGui`_

LUE_DATA_MODEL_WITH_PYTHON_API and LUE_FRAMEWORK_WITH_PYTHON_API
- `GDAL`_
- `HPX`_
- `Boost`_
- `HDF5`_
- `fmt`_
- `nlohmann-json3-dev`_
- `NumPy`_
- `Pybind11`_

LUE_DATA_MODEL_WITH_UTILITIES
- `GDAL`_
- `HPX`_
- `Boost`_
- `HDF5`_
- `fmt`_
- `nlohmann-json3-dev`_
- `docopt`_

2024-06-21 05:55 UTC, kordejong commented on document/doc/code/index.rst
I only meant that you could add this to the existing version, not to list the dependencies per target. This amount of detail is not needed. Just revert this file to the original version, but add a comment that the dependencies depend on the targets being built.

2024-06-24 10:33 UTC, kordejong approved these changes

2024-06-24 10:34 UTC, merged